# Generated by Django 3.2 on 2026-04-21 14:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicpost',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_music', to=settings.AUTH_USER_MODEL, verbose_name='いいね'),
        ),
    ]
