# Generated by Django 3.2 on 2026-04-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_musicpost_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicpost',
            name='image',
            field=models.ImageField(default='', upload_to='images/', verbose_name='画像ファイル'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='musicpost',
            name='music_file',
            field=models.FileField(default='', upload_to='music_files/', verbose_name='音楽ファイル'),
            preserve_default=False,
        ),
    ]
